In [1]:
import os
import numpy as np
import cv2
import torch
from torch.utils.data import Dataset


class CoronarySmallDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.images = os.listdir(image_dir)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.images[idx])
        mask_path = os.path.join(self.mask_dir, self.images[idx])
        

        image = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
        image = cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)
        image = cv2.resize(image, (256, 256))
        
        mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
        mask = cv2.cvtColor(mask, cv2.COLOR_RGBA2RGB)
        mask = cv2.resize(mask, (256, 256))
        
        if self.transform:
            image = self.transform(image)
            mask = self.transform(mask)
        
        return image, mask

In [2]:
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torchvision import transforms


transform = transforms.Compose([
    transforms.ToTensor()
])

train_image_dir = 'images_train\input'
train_mask_dir = 'images_train\output'
val_image_dir = 'images_val\input'
val_mask_dir = 'images_val\output'
test_image_dir = 'images_test\input'
test_mask_dir = 'images_test\output'

train_dataset = CoronarySmallDataset(train_image_dir, train_mask_dir, transform=transform)
val_dataset = CoronarySmallDataset(val_image_dir, val_mask_dir, transform=transform)
test_dataset = CoronarySmallDataset(test_image_dir, test_mask_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)


In [3]:
from medium_RGB_model import UNet


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = UNet()
model = model.to(device)

In [4]:
import torch.optim as optim
from tqdm import tqdm
import torch.nn as nn
import torch.nn.functional as F


criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

def train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=50):
    best_loss = float('inf')
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        for images, masks in tqdm(train_loader):
            images = images.to(device)
            masks = masks.to(device)

            # print(images.size())
            # print(images)
            # print(masks.size())
            # print(masks)

            optimizer.zero_grad()
            outputs = model(images)

            # print(outputs.size())
            # print(outputs)
            
            loss = criterion(outputs, masks)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item() * images.size(0)
        
        train_loss = train_loss / len(train_loader.dataset)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images = images.to(device)
                masks = masks.to(device)

                outputs = model(images)
                loss = criterion(outputs, masks)
                
                val_loss += loss.item() * images.size(0)
        
        val_loss = val_loss / len(val_loader.dataset)
        
        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')
        
        if val_loss < best_loss:
            best_loss = val_loss
            torch.save(model.state_dict(), 'medium_RGB_model.pth')


In [5]:
train_model(model, train_loader, val_loader, criterion, optimizer)

100%|██████████| 61/61 [01:40<00:00,  1.65s/it]


Epoch 1/50, Train Loss: 0.6271, Val Loss: 0.6203


100%|██████████| 61/61 [01:45<00:00,  1.73s/it]


Epoch 2/50, Train Loss: 0.6024, Val Loss: 0.6071


100%|██████████| 61/61 [01:48<00:00,  1.78s/it]


Epoch 3/50, Train Loss: 0.5944, Val Loss: 0.6038


100%|██████████| 61/61 [01:54<00:00,  1.88s/it]


Epoch 4/50, Train Loss: 0.5896, Val Loss: 0.6031


100%|██████████| 61/61 [01:57<00:00,  1.92s/it]


Epoch 5/50, Train Loss: 0.5864, Val Loss: 0.5984


100%|██████████| 61/61 [01:57<00:00,  1.93s/it]


Epoch 6/50, Train Loss: 0.5843, Val Loss: 0.5984


100%|██████████| 61/61 [02:16<00:00,  2.24s/it]


Epoch 7/50, Train Loss: 0.5830, Val Loss: 0.5959


100%|██████████| 61/61 [02:10<00:00,  2.13s/it]


Epoch 8/50, Train Loss: 0.5816, Val Loss: 0.5960


100%|██████████| 61/61 [01:57<00:00,  1.92s/it]


Epoch 9/50, Train Loss: 0.5807, Val Loss: 0.5953


100%|██████████| 61/61 [01:57<00:00,  1.92s/it]


Epoch 10/50, Train Loss: 0.5799, Val Loss: 0.5946


100%|██████████| 61/61 [01:57<00:00,  1.93s/it]


Epoch 11/50, Train Loss: 0.5793, Val Loss: 0.5941


100%|██████████| 61/61 [01:53<00:00,  1.86s/it]


Epoch 12/50, Train Loss: 0.5788, Val Loss: 0.5950


100%|██████████| 61/61 [01:56<00:00,  1.90s/it]


Epoch 13/50, Train Loss: 0.5784, Val Loss: 0.5946


100%|██████████| 61/61 [01:57<00:00,  1.92s/it]


Epoch 14/50, Train Loss: 0.5781, Val Loss: 0.5941


100%|██████████| 61/61 [01:55<00:00,  1.89s/it]


Epoch 15/50, Train Loss: 0.5777, Val Loss: 0.5949


100%|██████████| 61/61 [01:57<00:00,  1.93s/it]


Epoch 16/50, Train Loss: 0.5771, Val Loss: 0.5938


100%|██████████| 61/61 [01:50<00:00,  1.82s/it]


Epoch 17/50, Train Loss: 0.5764, Val Loss: 0.5947


100%|██████████| 61/61 [01:51<00:00,  1.83s/it]


Epoch 18/50, Train Loss: 0.5764, Val Loss: 0.5946


100%|██████████| 61/61 [01:50<00:00,  1.81s/it]


Epoch 19/50, Train Loss: 0.5758, Val Loss: 0.5942


100%|██████████| 61/61 [01:48<00:00,  1.78s/it]


Epoch 20/50, Train Loss: 0.5759, Val Loss: 0.5947


100%|██████████| 61/61 [01:49<00:00,  1.79s/it]


Epoch 21/50, Train Loss: 0.5751, Val Loss: 0.5945


100%|██████████| 61/61 [01:47<00:00,  1.77s/it]


Epoch 22/50, Train Loss: 0.5748, Val Loss: 0.5944


100%|██████████| 61/61 [01:47<00:00,  1.77s/it]


Epoch 23/50, Train Loss: 0.5745, Val Loss: 0.5945


100%|██████████| 61/61 [01:51<00:00,  1.83s/it]


Epoch 24/50, Train Loss: 0.5742, Val Loss: 0.5952


100%|██████████| 61/61 [01:49<00:00,  1.80s/it]


Epoch 25/50, Train Loss: 0.5739, Val Loss: 0.5953


  7%|▋         | 4/61 [00:09<02:08,  2.26s/it]


KeyboardInterrupt: 

In [9]:
import os
import numpy as np
import cv2
import torch
from torchvision import transforms


model.load_state_dict(torch.load('medium_RGB_model.pth'))
model.eval()

def show_image(type, image_name):
    dir = f"images_test\{type}"
    print(dir)
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    cv2.imshow(type, img)

def predict(image_name):
    dir = 'images_test\input'
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        print(pred)
        # pred = (pred > 0.5).astype(np.uint8)
    R, G, B = pred[0], pred[1], pred[2]
    # cv2.imshow('R', R)
    # cv2.imshow('G', G)
    # cv2.imshow('B', B)
    pred_image = np.zeros((256, 256, 3), dtype=np.uint8)
    pred_image[..., 0] = (R * 255).astype(np.uint8)
    pred_image[..., 1] = (G * 255).astype(np.uint8)
    pred_image[..., 2] = (B * 255).astype(np.uint8)
    print(pred_image)
    cv2.imshow('pred', pred_image)
    cv2.waitKey(0)
   

In [12]:
# image_name = "131aedfhs6pnf1fvtvp49mn3wvbw9rzr22_35.png"
# image_name = "131aedfhs6pnf1fvtvp49mh7xyoqut9g22_27.png"
image_name = "131aedfhs6pnf1fvtvp49ee0ulyq7shj22_40.png"
show_image("input", image_name)
show_image("output", image_name)
predict(image_name)

images_test\input
images_test\output
[[[0.5000489  0.43836886 0.43809673 ... 0.7696181  0.71902937 0.70230514]
  [0.42940557 0.43823823 0.42416936 ... 0.79144377 0.78251743 0.748417  ]
  [0.38490602 0.42659277 0.41706324 ... 0.80790776 0.836219   0.8037614 ]
  ...
  [0.42707035 0.4752605  0.48463124 ... 0.83051753 0.8462161  0.7774457 ]
  [0.43681854 0.4775517  0.4730061  ... 0.8074678  0.8150632  0.76215315]
  [0.4579239  0.45334584 0.45888922 ... 0.7410098  0.7628323  0.6696614 ]]

 [[0.47411597 0.49065426 0.44980326 ... 0.7971483  0.72762376 0.6964441 ]
  [0.40162277 0.400003   0.37782088 ... 0.8015171  0.76297086 0.73617774]
  [0.37309554 0.4090471  0.38657686 ... 0.79447764 0.8117419  0.8256982 ]
  ...
  [0.44839823 0.42986864 0.4663482  ... 0.8330308  0.8553282  0.8255221 ]
  [0.46743134 0.4266703  0.50105214 ... 0.81970894 0.87594086 0.81958055]
  [0.4636299  0.44402155 0.4465549  ... 0.7769037  0.78966457 0.69888484]]

 [[0.5020088  0.50456184 0.4381648  ... 0.80604184 0.705822

In [11]:
model.load_state_dict(torch.load('medium_RGB_model.pth'))

def dice_coefficient(y_true, y_pred):
    smooth = 1.0
    y_true_f = y_true.view(-1)
    y_pred_f = y_pred.view(-1)
    intersection = (y_true_f * y_pred_f).sum()
    return (2. * intersection + smooth) / (y_true_f.sum() + y_pred_f.sum() + smooth)

model.eval()
test_loss = 0.0
dice_scores = []

with torch.no_grad():
    for images, masks in test_loader:
        images = images.to(device)
        masks = masks.to(device)

        outputs = model(images)
        loss = criterion(outputs, masks)
        
        test_loss += loss.item() * images.size(0)
        dice_scores.append(dice_coefficient(masks, outputs))

test_loss = test_loss / len(test_loader.dataset)
mean_dice = torch.mean(torch.tensor(dice_scores))

print(f'Test Loss: {test_loss:.4f}')
print(f'Mean Dice Coefficient: {mean_dice:.4f}')


Test Loss: 0.5773
Mean Dice Coefficient: 0.6904


In [ ]:
from skimage import morphology

def post_process(prediction):
    prediction_np = prediction.cpu().numpy()
    processed = morphology.remove_small_objects(prediction_np > 0.5, min_size=100)
    processed = morphology.remove_small_holes(processed, area_threshold=100)
    return torch.tensor(processed, device=device)

post_processed_predictions = [post_process(pred) for pred in outputs]


In [ ]:
from flask import Flask, request, jsonify
import io

app = Flask(__name__)
model.load_state_dict(torch.load('model.pth'))
model.eval()

@app.route('/predict', methods=['POST'])
def predict():
    file = request.files['image']
    img_bytes = file.read()
    img = cv2.imdecode(np.frombuffer(img_bytes, np.uint8), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
    img = cv2.resize(img, (512, 512))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        pred = (pred > 0.5).astype(np.uint8)
    
    _, buffer = cv2.imencode('.png', pred)
    response = io.BytesIO(buffer)
    response.seek(0)
    return response, 200, {'Content-Type': 'image/png'}

if __name__ == '__main__':
    app.run()
