In [2]:
import os
import numpy as np
import cv2
import torch
from torch.utils.data import Dataset


class CoronarySmallDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.images = os.listdir(image_dir)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.images[idx])
        mask_path = os.path.join(self.mask_dir, self.images[idx])
        

        image = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
        image = cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)
        image = cv2.resize(image, (256, 256))
        
        mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
        mask = cv2.cvtColor(mask, cv2.COLOR_RGBA2RGB)
        mask = cv2.resize(mask, (256, 256))
        
        if self.transform:
            image = self.transform(image)
            mask = self.transform(mask)
        
        return image, mask

In [3]:
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torchvision import transforms


transform = transforms.Compose([
    transforms.ToTensor()
])

train_image_dir = 'images_train\input'
train_mask_dir = 'images_train\output'
val_image_dir = 'images_val\input'
val_mask_dir = 'images_val\output'
test_image_dir = 'images_test\input'
test_mask_dir = 'images_test\output'

train_dataset = CoronarySmallDataset(train_image_dir, train_mask_dir, transform=transform)
val_dataset = CoronarySmallDataset(val_image_dir, val_mask_dir, transform=transform)
test_dataset = CoronarySmallDataset(test_image_dir, test_mask_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)


In [4]:
from small_RGB_model import UNet


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = UNet()
model = model.to(device)

In [5]:
import torch.optim as optim
from tqdm import tqdm
import torch.nn as nn
import torch.nn.functional as F


criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

def train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=50):
    best_loss = float('inf')
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        for images, masks in tqdm(train_loader):
            images = images.to(device)
            masks = masks.to(device)

            # print(images.size())
            # print(images)
            # print(masks.size())
            # print(masks)

            optimizer.zero_grad()
            outputs = model(images)

            # print(outputs.size())
            # print(outputs)
            
            loss = criterion(outputs, masks)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item() * images.size(0)
        
        train_loss = train_loss / len(train_loader.dataset)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images = images.to(device)
                masks = masks.to(device)

                outputs = model(images)
                loss = criterion(outputs, masks)
                
                val_loss += loss.item() * images.size(0)
        
        val_loss = val_loss / len(val_loader.dataset)
        
        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')
        
        if val_loss < best_loss:
            best_loss = val_loss
            torch.save(model.state_dict(), 'small_RGB_model.pth')


In [5]:
train_model(model, train_loader, val_loader, criterion, optimizer)

100%|██████████| 61/61 [01:33<00:00,  1.53s/it]


Epoch 1/50, Train Loss: 0.6483, Val Loss: 0.6379


100%|██████████| 61/61 [01:38<00:00,  1.62s/it]


Epoch 2/50, Train Loss: 0.6172, Val Loss: 0.6226


100%|██████████| 61/61 [01:38<00:00,  1.62s/it]


Epoch 3/50, Train Loss: 0.6071, Val Loss: 0.6117


100%|██████████| 61/61 [01:39<00:00,  1.63s/it]


Epoch 4/50, Train Loss: 0.5998, Val Loss: 0.6087


100%|██████████| 61/61 [01:52<00:00,  1.85s/it]


Epoch 5/50, Train Loss: 0.5948, Val Loss: 0.6066


100%|██████████| 61/61 [01:47<00:00,  1.76s/it]


Epoch 6/50, Train Loss: 0.5912, Val Loss: 0.6047


100%|██████████| 61/61 [01:48<00:00,  1.78s/it]


Epoch 7/50, Train Loss: 0.5882, Val Loss: 0.6018


100%|██████████| 61/61 [01:43<00:00,  1.70s/it]


Epoch 8/50, Train Loss: 0.5858, Val Loss: 0.6000


100%|██████████| 61/61 [01:54<00:00,  1.88s/it]


Epoch 9/50, Train Loss: 0.5840, Val Loss: 0.5978


100%|██████████| 61/61 [01:45<00:00,  1.73s/it]


Epoch 10/50, Train Loss: 0.5827, Val Loss: 0.5972


100%|██████████| 61/61 [01:49<00:00,  1.80s/it]


Epoch 11/50, Train Loss: 0.5819, Val Loss: 0.5957


100%|██████████| 61/61 [01:49<00:00,  1.79s/it]


Epoch 12/50, Train Loss: 0.5812, Val Loss: 0.5947


100%|██████████| 61/61 [01:40<00:00,  1.65s/it]


Epoch 13/50, Train Loss: 0.5803, Val Loss: 0.5950


100%|██████████| 61/61 [01:42<00:00,  1.69s/it]


Epoch 14/50, Train Loss: 0.5797, Val Loss: 0.5949


100%|██████████| 61/61 [01:42<00:00,  1.67s/it]


Epoch 15/50, Train Loss: 0.5794, Val Loss: 0.5954


100%|██████████| 61/61 [01:42<00:00,  1.67s/it]


Epoch 16/50, Train Loss: 0.5794, Val Loss: 0.5942


100%|██████████| 61/61 [01:41<00:00,  1.67s/it]


Epoch 17/50, Train Loss: 0.5786, Val Loss: 0.5942


100%|██████████| 61/61 [01:41<00:00,  1.66s/it]


Epoch 18/50, Train Loss: 0.5785, Val Loss: 0.5951


100%|██████████| 61/61 [01:42<00:00,  1.68s/it]


Epoch 19/50, Train Loss: 0.5785, Val Loss: 0.5957


100%|██████████| 61/61 [01:42<00:00,  1.68s/it]


Epoch 20/50, Train Loss: 0.5779, Val Loss: 0.5943


100%|██████████| 61/61 [01:42<00:00,  1.68s/it]


Epoch 21/50, Train Loss: 0.5777, Val Loss: 0.5944


100%|██████████| 61/61 [01:42<00:00,  1.67s/it]


Epoch 22/50, Train Loss: 0.5773, Val Loss: 0.5948


100%|██████████| 61/61 [01:42<00:00,  1.68s/it]


Epoch 23/50, Train Loss: 0.5773, Val Loss: 0.5961


100%|██████████| 61/61 [01:42<00:00,  1.67s/it]


Epoch 24/50, Train Loss: 0.5768, Val Loss: 0.5943


100%|██████████| 61/61 [01:42<00:00,  1.69s/it]


Epoch 25/50, Train Loss: 0.5768, Val Loss: 0.5947


  7%|▋         | 4/61 [00:08<01:55,  2.03s/it]


KeyboardInterrupt: 

In [6]:
import os
import numpy as np
import cv2
import torch
from torchvision import transforms


model.load_state_dict(torch.load('small_RGB_model.pth'))
model.eval()

def show_image(type, image_name):
    dir = f"images_test\{type}"
    print(dir)
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    cv2.imshow(type, img)

def predict(image_name):
    dir = 'images_test\input'
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        print(pred)
        # pred = (pred > 0.5).astype(np.uint8)
    R, G, B = pred[0], pred[1], pred[2]
    # cv2.imshow('R', R)
    # cv2.imshow('G', G)
    # cv2.imshow('B', B)
    pred_image = np.zeros((256, 256, 3), dtype=np.uint8)
    pred_image[..., 0] = (R * 255).astype(np.uint8)
    pred_image[..., 1] = (G * 255).astype(np.uint8)
    pred_image[..., 2] = (B * 255).astype(np.uint8)
    print(pred_image)
    cv2.imshow('pred', pred_image)
    cv2.waitKey(0)
   

In [8]:
# image_name = "13c2ur549vohc0jat2dvu3xs7q1_18.png"
# image_name = "13c2ur549vohc0jat2wd23me01_25.png"
# image_name = "131aedfhs6pnf1fvtvp49h4bhdjeabmt22_31.png"
# image_name = "131aedfhs6pnf1fvtvp49juwu7plj9dv22_40.png"
show_image("input", image_name)
show_image("output", image_name)
predict(image_name)

images_test\input
images_test\output
[[[0.6962591  0.8756447  0.882192   ... 0.7521747  0.6642449  0.58956575]
  [0.83903307 0.9109458  0.9290688  ... 0.74359477 0.76048416 0.6666809 ]
  [0.8559474  0.9291461  0.94103044 ... 0.7251262  0.7425367  0.7119111 ]
  ...
  [0.63436574 0.5917953  0.5986272  ... 0.48382372 0.49626902 0.4878516 ]
  [0.6253845  0.6225618  0.5925777  ... 0.52380085 0.5152993  0.5070476 ]
  [0.5762267  0.6337912  0.61640495 ... 0.5415436  0.50644314 0.5635753 ]]

 [[0.73444766 0.8255866  0.87497485 ... 0.7393646  0.63334715 0.57304937]
  [0.83904034 0.8842644  0.90508693 ... 0.7421238  0.71939754 0.6591451 ]
  [0.8194916  0.8839403  0.92375815 ... 0.7399418  0.7550091  0.729922  ]
  ...
  [0.6067703  0.60201824 0.61113393 ... 0.47453985 0.46428302 0.4615907 ]
  [0.63977015 0.68113375 0.6065186  ... 0.5045319  0.4852583  0.48499098]
  [0.57809573 0.68662757 0.5857843  ... 0.51519096 0.48840854 0.53971267]]

 [[0.70253503 0.8670708  0.88914335 ... 0.7558567  0.670927

In [41]:
model.load_state_dict(torch.load('small_RGB_model.pth'))

def dice_coefficient(y_true, y_pred):
    smooth = 1.0
    y_true_f = y_true.view(-1)
    y_pred_f = y_pred.view(-1)
    intersection = (y_true_f * y_pred_f).sum()
    return (2. * intersection + smooth) / (y_true_f.sum() + y_pred_f.sum() + smooth)

model.eval()
test_loss = 0.0
dice_scores = []

with torch.no_grad():
    for images, masks in test_loader:
        images = images.to(device)
        masks = masks.to(device)

        outputs = model(images)
        loss = criterion(outputs, masks)
        
        test_loss += loss.item() * images.size(0)
        dice_scores.append(dice_coefficient(masks, outputs))

test_loss = test_loss / len(test_loader.dataset)
mean_dice = torch.mean(torch.tensor(dice_scores))

print(f'Test Loss: {test_loss:.4f}')
print(f'Mean Dice Coefficient: {mean_dice:.4f}')


Test Loss: 0.5778
Mean Dice Coefficient: 0.6897


In [ ]:
from skimage import morphology

def post_process(prediction):
    prediction_np = prediction.cpu().numpy()
    processed = morphology.remove_small_objects(prediction_np > 0.5, min_size=100)
    processed = morphology.remove_small_holes(processed, area_threshold=100)
    return torch.tensor(processed, device=device)

post_processed_predictions = [post_process(pred) for pred in outputs]


In [ ]:
from flask import Flask, request, jsonify
import io

app = Flask(__name__)
model.load_state_dict(torch.load('model.pth'))
model.eval()

@app.route('/predict', methods=['POST'])
def predict():
    file = request.files['image']
    img_bytes = file.read()
    img = cv2.imdecode(np.frombuffer(img_bytes, np.uint8), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
    img = cv2.resize(img, (512, 512))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        pred = (pred > 0.5).astype(np.uint8)
    
    _, buffer = cv2.imencode('.png', pred)
    response = io.BytesIO(buffer)
    response.seek(0)
    return response, 200, {'Content-Type': 'image/png'}

if __name__ == '__main__':
    app.run()
