In [1]:
import os
import numpy as np
import cv2
import torch
from torch.utils.data import Dataset


class CoronarySmallDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.images = os.listdir(image_dir)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.images[idx])
        mask_path = os.path.join(self.mask_dir, self.images[idx])
        

        image = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
        image = cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)
        image = cv2.resize(image, (256, 256))
        
        mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
        mask = cv2.cvtColor(mask, cv2.COLOR_RGBA2RGB)
        mask = cv2.resize(mask, (256, 256))
        
        if self.transform:
            image = self.transform(image)
            mask = self.transform(mask)
        
        return image, mask

In [2]:
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torchvision import transforms


transform = transforms.Compose([
    transforms.ToTensor()
])

train_image_dir = 'images_train\input'
train_mask_dir = 'images_train\output'
val_image_dir = 'images_val\input'
val_mask_dir = 'images_val\output'
test_image_dir = 'images_test\input'
test_mask_dir = 'images_test\output'

train_dataset = CoronarySmallDataset(train_image_dir, train_mask_dir, transform=transform)
val_dataset = CoronarySmallDataset(val_image_dir, val_mask_dir, transform=transform)
test_dataset = CoronarySmallDataset(test_image_dir, test_mask_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)


In [3]:
from large_RGB_model import UNet


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = UNet()
model = model.to(device)

In [4]:
import torch.optim as optim
from tqdm import tqdm
import torch.nn as nn
import torch.nn.functional as F


criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

def train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=50):
    best_loss = float('inf')
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        for images, masks in tqdm(train_loader):
            images = images.to(device)
            masks = masks.to(device)

            # print(images.size())
            # print(images)
            # print(masks.size())
            # print(masks)

            optimizer.zero_grad()
            outputs = model(images)

            # print(outputs.size())
            # print(outputs)
            
            loss = criterion(outputs, masks)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item() * images.size(0)
        
        train_loss = train_loss / len(train_loader.dataset)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images = images.to(device)
                masks = masks.to(device)

                outputs = model(images)
                loss = criterion(outputs, masks)
                
                val_loss += loss.item() * images.size(0)
        
        val_loss = val_loss / len(val_loader.dataset)
        
        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')
        
        if val_loss < best_loss:
            best_loss = val_loss
            torch.save(model.state_dict(), 'large_RGB_model.pth')


In [5]:
train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=50)

100%|██████████| 70/70 [04:28<00:00,  3.84s/it]


Epoch 1/50, Train Loss: 0.5677, Val Loss: 0.5015


100%|██████████| 70/70 [04:41<00:00,  4.03s/it]


Epoch 2/50, Train Loss: 0.4498, Val Loss: 0.4201


100%|██████████| 70/70 [04:54<00:00,  4.20s/it]


Epoch 3/50, Train Loss: 0.3850, Val Loss: 0.3584


100%|██████████| 70/70 [05:03<00:00,  4.33s/it]


Epoch 4/50, Train Loss: 0.3334, Val Loss: 0.3168


100%|██████████| 70/70 [05:15<00:00,  4.50s/it]


Epoch 5/50, Train Loss: 0.2908, Val Loss: 0.2750


100%|██████████| 70/70 [05:21<00:00,  4.59s/it]


Epoch 6/50, Train Loss: 0.2592, Val Loss: 0.2438


100%|██████████| 70/70 [05:23<00:00,  4.62s/it]


Epoch 7/50, Train Loss: 0.2263, Val Loss: 0.2174


100%|██████████| 70/70 [05:23<00:00,  4.62s/it]


Epoch 8/50, Train Loss: 0.2009, Val Loss: 0.1999


100%|██████████| 70/70 [05:15<00:00,  4.51s/it]


Epoch 9/50, Train Loss: 0.1797, Val Loss: 0.1719


100%|██████████| 70/70 [05:18<00:00,  4.55s/it]


Epoch 10/50, Train Loss: 0.1604, Val Loss: 0.1503


100%|██████████| 70/70 [05:19<00:00,  4.56s/it]


Epoch 11/50, Train Loss: 0.1439, Val Loss: 0.1381


100%|██████████| 70/70 [05:20<00:00,  4.57s/it]


Epoch 12/50, Train Loss: 0.1291, Val Loss: 0.1236


100%|██████████| 70/70 [05:25<00:00,  4.65s/it]


Epoch 13/50, Train Loss: 0.1173, Val Loss: 0.1118


100%|██████████| 70/70 [05:28<00:00,  4.69s/it]


Epoch 14/50, Train Loss: 0.1072, Val Loss: 0.1029


100%|██████████| 70/70 [05:33<00:00,  4.76s/it]


Epoch 15/50, Train Loss: 0.0988, Val Loss: 0.0956


100%|██████████| 70/70 [05:30<00:00,  4.72s/it]


Epoch 16/50, Train Loss: 0.0915, Val Loss: 0.0903


100%|██████████| 70/70 [05:34<00:00,  4.77s/it]


Epoch 17/50, Train Loss: 0.0853, Val Loss: 0.0844


100%|██████████| 70/70 [05:37<00:00,  4.83s/it]


Epoch 18/50, Train Loss: 0.0797, Val Loss: 0.0788


100%|██████████| 70/70 [05:38<00:00,  4.84s/it]


Epoch 19/50, Train Loss: 0.0748, Val Loss: 0.0742


100%|██████████| 70/70 [05:39<00:00,  4.85s/it]


Epoch 20/50, Train Loss: 0.0704, Val Loss: 0.0713


100%|██████████| 70/70 [05:40<00:00,  4.86s/it]


Epoch 21/50, Train Loss: 0.0668, Val Loss: 0.0676


100%|██████████| 70/70 [05:39<00:00,  4.85s/it]


Epoch 22/50, Train Loss: 0.0631, Val Loss: 0.0634


100%|██████████| 70/70 [05:36<00:00,  4.81s/it]


Epoch 23/50, Train Loss: 0.0600, Val Loss: 0.0618


100%|██████████| 70/70 [05:36<00:00,  4.80s/it]


Epoch 24/50, Train Loss: 0.0571, Val Loss: 0.0578


100%|██████████| 70/70 [05:40<00:00,  4.86s/it]


Epoch 25/50, Train Loss: 0.0546, Val Loss: 0.0556


100%|██████████| 70/70 [05:39<00:00,  4.86s/it]


Epoch 26/50, Train Loss: 0.0524, Val Loss: 0.0544


100%|██████████| 70/70 [05:29<00:00,  4.71s/it]


Epoch 27/50, Train Loss: 0.0503, Val Loss: 0.0521


100%|██████████| 70/70 [05:28<00:00,  4.69s/it]


Epoch 28/50, Train Loss: 0.0484, Val Loss: 0.0504


100%|██████████| 70/70 [05:27<00:00,  4.68s/it]


Epoch 29/50, Train Loss: 0.0466, Val Loss: 0.0497


100%|██████████| 70/70 [05:31<00:00,  4.73s/it]


Epoch 30/50, Train Loss: 0.0451, Val Loss: 0.0475


100%|██████████| 70/70 [05:32<00:00,  4.75s/it]


Epoch 31/50, Train Loss: 0.0436, Val Loss: 0.0466


100%|██████████| 70/70 [05:27<00:00,  4.68s/it]


Epoch 32/50, Train Loss: 0.0424, Val Loss: 0.0457


100%|██████████| 70/70 [05:27<00:00,  4.67s/it]


Epoch 33/50, Train Loss: 0.0409, Val Loss: 0.0444


100%|██████████| 70/70 [05:30<00:00,  4.71s/it]


Epoch 34/50, Train Loss: 0.0396, Val Loss: 0.0434


100%|██████████| 70/70 [05:30<00:00,  4.72s/it]


Epoch 35/50, Train Loss: 0.0388, Val Loss: 0.0429


100%|██████████| 70/70 [05:29<00:00,  4.70s/it]


Epoch 36/50, Train Loss: 0.0376, Val Loss: 0.0436


100%|██████████| 70/70 [05:29<00:00,  4.71s/it]


Epoch 37/50, Train Loss: 0.0365, Val Loss: 0.0428


100%|██████████| 70/70 [05:29<00:00,  4.70s/it]


Epoch 38/50, Train Loss: 0.0356, Val Loss: 0.0419


100%|██████████| 70/70 [05:31<00:00,  4.74s/it]


Epoch 39/50, Train Loss: 0.0348, Val Loss: 0.0403


100%|██████████| 70/70 [05:31<00:00,  4.73s/it]


Epoch 40/50, Train Loss: 0.0340, Val Loss: 0.0402


100%|██████████| 70/70 [05:28<00:00,  4.70s/it]


Epoch 41/50, Train Loss: 0.0329, Val Loss: 0.0403


100%|██████████| 70/70 [05:30<00:00,  4.72s/it]


Epoch 42/50, Train Loss: 0.0323, Val Loss: 0.0393


100%|██████████| 70/70 [05:30<00:00,  4.73s/it]


Epoch 43/50, Train Loss: 0.0314, Val Loss: 0.0394


100%|██████████| 70/70 [05:29<00:00,  4.70s/it]


Epoch 44/50, Train Loss: 0.0306, Val Loss: 0.0393


100%|██████████| 70/70 [05:31<00:00,  4.73s/it]


Epoch 45/50, Train Loss: 0.0301, Val Loss: 0.0385


100%|██████████| 70/70 [05:31<00:00,  4.73s/it]


Epoch 46/50, Train Loss: 0.0293, Val Loss: 0.0387


100%|██████████| 70/70 [05:30<00:00,  4.73s/it]


Epoch 47/50, Train Loss: 0.0288, Val Loss: 0.0388


100%|██████████| 70/70 [05:29<00:00,  4.71s/it]


Epoch 48/50, Train Loss: 0.0282, Val Loss: 0.0395


100%|██████████| 70/70 [05:29<00:00,  4.71s/it]


Epoch 49/50, Train Loss: 0.0278, Val Loss: 0.0377


100%|██████████| 70/70 [05:31<00:00,  4.74s/it]


Epoch 50/50, Train Loss: 0.0274, Val Loss: 0.0384


In [4]:
import os
import numpy as np
import cv2
import torch
from torchvision import transforms


model.load_state_dict(torch.load('large_RGB_model.pth'))
model.eval()

def show_image(type, image_name):
    dir = f"images_test\{type}"
    print(dir)
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (512, 512))
    cv2.imshow(type, img)

def predict(image_name):
    dir = 'images_test\input'
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        print(pred)
        # pred = (pred > 0.5).astype(np.uint8)
    R, G, B = pred[0], pred[1], pred[2]
    # cv2.imshow('R', R)
    # cv2.imshow('G', G)
    # cv2.imshow('B', B)
    pred_image = np.zeros((256, 256, 3), dtype=np.uint8)
    pred_image[..., 0] = (R * 255).astype(np.uint8)
    pred_image[..., 1] = (G * 255).astype(np.uint8)
    pred_image[..., 2] = (B * 255).astype(np.uint8)
    # print(pred_image)
    # cv2.imshow('pred0', pred_image)
    bigger_image = cv2.resize(pred_image, (512, 512))
    cv2.imshow('pred', bigger_image)
    cv2.waitKey(0)
   

In [8]:
# image_name = "131aedfhs6pnf1fvtvp49mhdb2fucqzo22_29.png"
# image_name = "131aedfhs6pnf1fvtvp49mld7mqexnz322_36.png"
# image_name = "131aedfhs6pnf1fvtvp49mia892s56cf22_28.png"
image_name = "131aedfhs6pnf1fvtvp49juwu7plj9dv22_40.png"
show_image("input", image_name)
show_image("output", image_name)
predict(image_name)

images_test\input
images_test\output
[[[0.00818609 0.00543319 0.00515106 ... 0.00465896 0.00575915 0.00841501]
  [0.00465184 0.00505169 0.00377884 ... 0.00443683 0.00383236 0.00557036]
  [0.00456213 0.00434043 0.00469404 ... 0.00418018 0.00415375 0.00481015]
  ...
  [0.00392881 0.00453922 0.00381806 ... 0.00368547 0.00350221 0.00427708]
  [0.00436291 0.00405042 0.00457177 ... 0.00405523 0.00513994 0.00687718]
  [0.00735469 0.00621082 0.00491621 ... 0.00449658 0.00530831 0.01630184]]

 [[0.00960791 0.00612023 0.00529056 ... 0.0051872  0.00531309 0.00884101]
  [0.00649424 0.00455892 0.0049583  ... 0.00405356 0.00528577 0.00506562]
  [0.00544822 0.0046508  0.00523467 ... 0.00447523 0.00424242 0.00534252]
  ...
  [0.00520213 0.00405806 0.00492703 ... 0.00478127 0.00448251 0.00448293]
  [0.00520192 0.00446592 0.00475409 ... 0.00502995 0.00666414 0.00712623]
  [0.00922494 0.00595375 0.00664968 ... 0.00500265 0.00625355 0.01295212]]

 [[0.00894965 0.00564089 0.00448417 ... 0.00477276 0.004403

In [ ]:
image_name = "131aedfhs6pnf1fvtvp49mia892s56cf22_28.png"
# image_name = "131aedfhs6pnf1fvtvp49juwu7plj9dv22_40.png"
show_image("input", image_name)
show_image("output", image_name)
predict(image_name)

In [ ]:
image_name = "131aedfhs6pnf1fvtvp49mia892s56cf22_28.png"
# image_name = "131aedfhs6pnf1fvtvp49juwu7plj9dv22_40.png"
show_image("input", image_name)
show_image("output", image_name)
predict(image_name)

In [11]:
model.load_state_dict(torch.load('large_RGB_model.pth'))

def dice_coefficient(y_true, y_pred):
    smooth = 1.0
    y_true_f = y_true.view(-1)
    y_pred_f = y_pred.view(-1)
    intersection = (y_true_f * y_pred_f).sum()
    return (2. * intersection + smooth) / (y_true_f.sum() + y_pred_f.sum() + smooth)

model.eval()
test_loss = 0.0
dice_scores = []

with torch.no_grad():
    for images, masks in test_loader:
        images = images.to(device)
        masks = masks.to(device)

        outputs = model(images)
        loss = criterion(outputs, masks)
        
        test_loss += loss.item() * images.size(0)
        dice_scores.append(dice_coefficient(masks, outputs))

test_loss = test_loss / len(test_loader.dataset)
mean_dice = torch.mean(torch.tensor(dice_scores))

print(f'Test Loss: {test_loss:.4f}')
print(f'Mean Dice Coefficient: {mean_dice:.4f}')


Test Loss: 0.5773
Mean Dice Coefficient: 0.6904


In [ ]:
from skimage import morphology

def post_process(prediction):
    prediction_np = prediction.cpu().numpy()
    processed = morphology.remove_small_objects(prediction_np > 0.5, min_size=100)
    processed = morphology.remove_small_holes(processed, area_threshold=100)
    return torch.tensor(processed, device=device)

post_processed_predictions = [post_process(pred) for pred in outputs]


In [ ]:
from flask import Flask, request, jsonify
import io

app = Flask(__name__)
model.load_state_dict(torch.load('model.pth'))
model.eval()

@app.route('/predict', methods=['POST'])
def predict():
    file = request.files['image']
    img_bytes = file.read()
    img = cv2.imdecode(np.frombuffer(img_bytes, np.uint8), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
    img = cv2.resize(img, (512, 512))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        pred = (pred > 0.5).astype(np.uint8)
    
    _, buffer = cv2.imencode('.png', pred)
    response = io.BytesIO(buffer)
    response.seek(0)
    return response, 200, {'Content-Type': 'image/png'}

if __name__ == '__main__':
    app.run()
