In [1]:
import os
import numpy as np
import cv2
import torch
from torch.utils.data import Dataset


class CoronarySmallDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.images = os.listdir(image_dir)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.images[idx])
        mask_path = os.path.join(self.mask_dir, self.images[idx])
        

        image = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
        image = cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)
        image = cv2.resize(image, (256, 256))
        
        mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
        mask = cv2.cvtColor(mask, cv2.COLOR_RGBA2RGB)
        mask = cv2.resize(mask, (256, 256))
        
        if self.transform:
            image = self.transform(image)
            mask = self.transform(mask)
        
        return image, mask

In [2]:
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from torchvision import transforms


transform = transforms.Compose([
    transforms.ToTensor()
])

train_image_dir = 'images_train\input'
train_mask_dir = 'images_train\output'
val_image_dir = 'images_val\input'
val_mask_dir = 'images_val\output'
test_image_dir = 'images_test\input'
test_mask_dir = 'images_test\output'

train_dataset = CoronarySmallDataset(train_image_dir, train_mask_dir, transform=transform)
val_dataset = CoronarySmallDataset(val_image_dir, val_mask_dir, transform=transform)
test_dataset = CoronarySmallDataset(test_image_dir, test_mask_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=12, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=12, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=12, shuffle=False)


In [3]:
from medium_RGB_model import UNet


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = UNet()
model = model.to(device)

In [4]:
import torch.optim as optim
from tqdm import tqdm
import torch.nn as nn
import torch.nn.functional as F


criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

def train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=50):
    best_loss = float('inf')
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        for images, masks in tqdm(train_loader):
            images = images.to(device)
            masks = masks.to(device)

            # print(images.size())
            # print(images)
            # print(masks.size())
            # print(masks)

            optimizer.zero_grad()
            outputs = model(images)

            # print(outputs.size())
            # print(outputs)
            
            loss = criterion(outputs, masks)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item() * images.size(0)
        
        train_loss = train_loss / len(train_loader.dataset)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images = images.to(device)
                masks = masks.to(device)

                outputs = model(images)
                loss = criterion(outputs, masks)
                
                val_loss += loss.item() * images.size(0)
        
        val_loss = val_loss / len(val_loader.dataset)
        
        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')
        
        if val_loss < best_loss:
            best_loss = val_loss
            torch.save(model.state_dict(), 'medium_RGB_model.pth')


In [5]:
train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=35)

100%|██████████| 47/47 [01:41<00:00,  2.17s/it]


Epoch 1/35, Train Loss: 0.6180, Val Loss: 0.5892


100%|██████████| 47/47 [01:50<00:00,  2.35s/it]


Epoch 2/35, Train Loss: 0.5500, Val Loss: 0.5329


100%|██████████| 47/47 [01:48<00:00,  2.31s/it]


Epoch 3/35, Train Loss: 0.5161, Val Loss: 0.5052


100%|██████████| 47/47 [01:49<00:00,  2.34s/it]


Epoch 4/35, Train Loss: 0.4883, Val Loss: 0.4749


100%|██████████| 47/47 [01:50<00:00,  2.36s/it]


Epoch 5/35, Train Loss: 0.4631, Val Loss: 0.4532


100%|██████████| 47/47 [01:51<00:00,  2.37s/it]


Epoch 6/35, Train Loss: 0.4389, Val Loss: 0.4266


100%|██████████| 47/47 [01:52<00:00,  2.40s/it]


Epoch 7/35, Train Loss: 0.4156, Val Loss: 0.4067


100%|██████████| 47/47 [01:55<00:00,  2.46s/it]


Epoch 8/35, Train Loss: 0.3932, Val Loss: 0.3842


100%|██████████| 47/47 [01:57<00:00,  2.50s/it]


Epoch 9/35, Train Loss: 0.3720, Val Loss: 0.3629


100%|██████████| 47/47 [02:07<00:00,  2.72s/it]


Epoch 10/35, Train Loss: 0.3519, Val Loss: 0.3456


100%|██████████| 47/47 [01:56<00:00,  2.49s/it]


Epoch 11/35, Train Loss: 0.3329, Val Loss: 0.3247


100%|██████████| 47/47 [01:50<00:00,  2.36s/it]


Epoch 12/35, Train Loss: 0.3145, Val Loss: 0.3064


100%|██████████| 47/47 [01:49<00:00,  2.34s/it]


Epoch 13/35, Train Loss: 0.2968, Val Loss: 0.2889


100%|██████████| 47/47 [01:50<00:00,  2.36s/it]


Epoch 14/35, Train Loss: 0.2798, Val Loss: 0.2725


100%|██████████| 47/47 [01:52<00:00,  2.39s/it]


Epoch 15/35, Train Loss: 0.2635, Val Loss: 0.2553


100%|██████████| 47/47 [01:50<00:00,  2.36s/it]


Epoch 16/35, Train Loss: 0.2479, Val Loss: 0.2420


100%|██████████| 47/47 [01:51<00:00,  2.38s/it]


Epoch 17/35, Train Loss: 0.2338, Val Loss: 0.2294


100%|██████████| 47/47 [01:49<00:00,  2.32s/it]


Epoch 18/35, Train Loss: 0.2207, Val Loss: 0.2169


100%|██████████| 47/47 [01:53<00:00,  2.41s/it]


Epoch 19/35, Train Loss: 0.2086, Val Loss: 0.2051


100%|██████████| 47/47 [01:49<00:00,  2.34s/it]


Epoch 20/35, Train Loss: 0.1975, Val Loss: 0.1926


100%|██████████| 47/47 [01:49<00:00,  2.34s/it]


Epoch 21/35, Train Loss: 0.1871, Val Loss: 0.1843


100%|██████████| 47/47 [02:03<00:00,  2.64s/it]


Epoch 22/35, Train Loss: 0.1772, Val Loss: 0.1752


100%|██████████| 47/47 [02:03<00:00,  2.62s/it]


Epoch 23/35, Train Loss: 0.1677, Val Loss: 0.1651


100%|██████████| 47/47 [02:15<00:00,  2.88s/it]


Epoch 24/35, Train Loss: 0.1589, Val Loss: 0.1573


100%|██████████| 47/47 [02:14<00:00,  2.86s/it]


Epoch 25/35, Train Loss: 0.1506, Val Loss: 0.1484


100%|██████████| 47/47 [02:12<00:00,  2.83s/it]


Epoch 26/35, Train Loss: 0.1428, Val Loss: 0.1418


100%|██████████| 47/47 [02:12<00:00,  2.82s/it]


Epoch 27/35, Train Loss: 0.1355, Val Loss: 0.1350


100%|██████████| 47/47 [01:55<00:00,  2.45s/it]


Epoch 28/35, Train Loss: 0.1287, Val Loss: 0.1279


100%|██████████| 47/47 [01:54<00:00,  2.43s/it]


Epoch 29/35, Train Loss: 0.1222, Val Loss: 0.1213


100%|██████████| 47/47 [01:56<00:00,  2.47s/it]


Epoch 30/35, Train Loss: 0.1163, Val Loss: 0.1159


100%|██████████| 47/47 [02:01<00:00,  2.59s/it]


Epoch 31/35, Train Loss: 0.1108, Val Loss: 0.1115


100%|██████████| 47/47 [02:04<00:00,  2.65s/it]


Epoch 32/35, Train Loss: 0.1057, Val Loss: 0.1057


100%|██████████| 47/47 [02:11<00:00,  2.79s/it]


Epoch 33/35, Train Loss: 0.1009, Val Loss: 0.1020


100%|██████████| 47/47 [02:19<00:00,  2.96s/it]


Epoch 34/35, Train Loss: 0.0966, Val Loss: 0.0978


100%|██████████| 47/47 [02:22<00:00,  3.03s/it]


Epoch 35/35, Train Loss: 0.0923, Val Loss: 0.0946


In [5]:
import os
import numpy as np
import cv2
import torch
from torchvision import transforms


model.load_state_dict(torch.load('medium_RGB_model.pth'))
model.eval()

def show_image(type, image_name):
    dir = f"images_test\{type}"
    print(dir)
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    cv2.imshow(type, img)

def predict(image_name):
    dir = 'images_test\input'
    img = cv2.imread(os.path.join(dir, image_name), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    img = cv2.resize(img, (256, 256))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        print(pred)
        # pred = (pred > 0.5).astype(np.uint8)
    R, G, B = pred[0], pred[1], pred[2]
    # cv2.imshow('R', R)
    # cv2.imshow('G', G)
    # cv2.imshow('B', B)
    pred_image = np.zeros((256, 256, 3), dtype=np.uint8)
    pred_image[..., 0] = (R * 255).astype(np.uint8)
    pred_image[..., 1] = (G * 255).astype(np.uint8)
    pred_image[..., 2] = (B * 255).astype(np.uint8)
    print(pred_image)
    cv2.imshow('pred', pred_image)
    cv2.waitKey(0)
   

In [9]:
# image_name = "13c2ur549vohc0jat2dvu3xs7q1_18.png"
# image_name = "13c2ur549vohc0jat2wd23me01_25.png"
# image_name = "131aedfhs6pnf1fvtvp49h4bhdjeabmt22_31.png"
# image_name = "131aedfhs6pnf1fvtvp49juwu7plj9dv22_40.png"
show_image("input", image_name)
show_image("output", image_name)
predict(image_name)

images_test\input
images_test\output
[[[0.06246718 0.06922256 0.05895988 ... 0.04856448 0.05051027 0.07822076]
  [0.06767297 0.0582726  0.07724336 ... 0.05335322 0.06814187 0.0592076 ]
  [0.05244011 0.05740533 0.05688231 ... 0.05359422 0.05517795 0.08688217]
  ...
  [0.05954779 0.04912103 0.07220041 ... 0.05501693 0.05996656 0.05422998]
  [0.04936417 0.05736936 0.05567563 ... 0.05995795 0.0517322  0.09486095]
  [0.07306532 0.05651188 0.07467362 ... 0.05443484 0.07152171 0.05348182]]

 [[0.0813878  0.10738065 0.07746644 ... 0.08434334 0.09520651 0.11754666]
  [0.10931675 0.0880686  0.11334766 ... 0.07558413 0.09863579 0.0964295 ]
  [0.06609856 0.07112847 0.07200418 ... 0.06606143 0.07336381 0.09913124]
  ...
  [0.10077146 0.06965933 0.10016512 ... 0.0798332  0.07984433 0.08416903]
  [0.06911609 0.07294392 0.07583224 ... 0.07108422 0.07475418 0.11453338]
  [0.12801865 0.08403397 0.10762579 ... 0.07158974 0.11191987 0.09133819]]

 [[0.0566926  0.05854304 0.05554635 ... 0.05666994 0.050730

In [11]:
model.load_state_dict(torch.load('medium_RGB_model.pth'))

def dice_coefficient(y_true, y_pred):
    smooth = 1.0
    y_true_f = y_true.view(-1)
    y_pred_f = y_pred.view(-1)
    intersection = (y_true_f * y_pred_f).sum()
    return (2. * intersection + smooth) / (y_true_f.sum() + y_pred_f.sum() + smooth)

model.eval()
test_loss = 0.0
dice_scores = []

with torch.no_grad():
    for images, masks in test_loader:
        images = images.to(device)
        masks = masks.to(device)

        outputs = model(images)
        loss = criterion(outputs, masks)
        
        test_loss += loss.item() * images.size(0)
        dice_scores.append(dice_coefficient(masks, outputs))

test_loss = test_loss / len(test_loader.dataset)
mean_dice = torch.mean(torch.tensor(dice_scores))

print(f'Test Loss: {test_loss:.4f}')
print(f'Mean Dice Coefficient: {mean_dice:.4f}')


Test Loss: 0.5773
Mean Dice Coefficient: 0.6904


In [ ]:
from skimage import morphology

def post_process(prediction):
    prediction_np = prediction.cpu().numpy()
    processed = morphology.remove_small_objects(prediction_np > 0.5, min_size=100)
    processed = morphology.remove_small_holes(processed, area_threshold=100)
    return torch.tensor(processed, device=device)

post_processed_predictions = [post_process(pred) for pred in outputs]


In [ ]:
from flask import Flask, request, jsonify
import io

app = Flask(__name__)
model.load_state_dict(torch.load('model.pth'))
model.eval()

@app.route('/predict', methods=['POST'])
def predict():
    file = request.files['image']
    img_bytes = file.read()
    img = cv2.imdecode(np.frombuffer(img_bytes, np.uint8), cv2.IMREAD_UNCHANGED)
    img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
    img = cv2.resize(img, (512, 512))
    img = transforms.ToTensor()(img).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img)
        pred = pred.squeeze().cpu().numpy()
        pred = (pred > 0.5).astype(np.uint8)
    
    _, buffer = cv2.imencode('.png', pred)
    response = io.BytesIO(buffer)
    response.seek(0)
    return response, 200, {'Content-Type': 'image/png'}

if __name__ == '__main__':
    app.run()
